version: 2

#release:
#  gitlab:
#    owner: dv
#    name: dv-updater
#  ids: [ ]
#  mode: replace

builds:
  - id: "dv-updater"
    main: "./cmd/app"
    binary: "dv-updater"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=gcc

    ldflags:
      - -installsuffix cgo
      - -s -w -X main.version={{.Tag}} -X main.commitHash={{.ShortCommit}}

gitlab_urls:
  api: https://maxgit.net/api/v4/
  download: https://maxgit.net

  skip_tls_verify: false
  use_package_registry: false
  use_job_token: true

nfpms:
  - id: "dv-updater"
    maintainer: "dv-updater"
    package_name: "dv-updater"
    formats:
      - rpm
      - deb
    bindir: /home/dv/updater
    builds:
      - "dv-updater"
    contents:
      - src: artifacts/dv-updater.service
        dst: /home/dv/updater/dv-updater.service
    scripts:
      preinstall: "artifacts/scripts/preinstall.sh"
      postinstall: "artifacts/scripts/postinstall.sh"
      preremove: "artifacts/scripts/preremove.sh"
      postremove: "artifacts/scripts/postremove.sh"

archives:
  - id: "dv-updater"
    format: binary

furies:
  - account: "{{ .Env.FURY_ACCOUNT }}"
  - formats:
      - rpm
      - deb
  - ids:
      - dv-updater

