version: 2

builds:
  - id: "dv-updater"
    main: "./cmd/app"
    binary: "dv-updater"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
      - CC=gcc

    ldflags:
      - -installsuffix cgo
      - -s -w -X main.version={{.Tag}} -X main.commitHash={{.ShortCommit}}

checksum:
  algorithm: sha1

nfpms:
  - id: "dv-updater"
    maintainer: "dv-updater"
    package_name: "dv-updater"
    formats:
      - rpm
      - deb
    bindir: /home/dv/updater
    builds:
      - "dv-updater"
    contents:
      - src: artifacts/dv-updater.service
        dst: /home/dv/updater/dv-updater.service
    scripts:
      preinstall: "artifacts/scripts/preinstall.sh"
      postinstall: "artifacts/scripts/postinstall.sh"
      preremove: "artifacts/scripts/preremove.sh"
      postremove: "artifacts/scripts/postremove.sh"
    rpm:
      signature:
        key_file:  artifacts/.keys/private.asc
    deb:
      signature:
        key_file: artifacts/.keys/private.asc
#        key_id: {{ .Env.GPG_FINGERPRINT }}

archives:
  - id: "dv-updater"
    format: binary




signs:
  - artifacts: all
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

furies:
  - account: "{{ .Env.FURY_ACCOUNT }}"
  - formats:
      - rpm
      - deb
  - ids:
      - dv-updater
