name: Release Stable

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release-rc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Clean dist
        run: rm -rf dist/*

      - name: Prepare Release Notes
        run: awk '/## \[/{flag=1;if(++i>1)exit;print;next;}/##/{flag=0;}flag' CHANGELOG.md >> artifacts/.release-notes/NOTES.md

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          distribution: goreleaser-pro
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          FURY_ACCOUNT: ${{ secrets.FURY_ACCOUNT_STABLE }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN_STABLE }}
